# Generated by Django 4.2.1 on 2024-07-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0005_alter_clients_district_id_alter_managers_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='наименование')),
                ('start_date', models.DateTimeField(verbose_name='дата начала')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнено')),
                ('actual_date', models.DateTimeField(verbose_name='дата фактического выполнения')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='ответственный')),
                ('responsible_rp', models.CharField(blank=True, max_length=200, verbose_name='ответственный рп')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.contracts', verbose_name='договоры')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'ordering': ['created_at'],
            },
        ),
    ]
