# Generated by Django 5.0.7 on 2024-08-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0005_alter_projects_options_remove_projects_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(verbose_name='срок выполнения'),
        ),
    ]
