# Generated by Django 5.0.7 on 2024-08-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0007_contracts_alter_projects_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='contract_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
