# Generated by Django 5.0.7 on 2024-08-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0008_contracts_contract_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='contract_id',
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
    ]
