# Generated by Django 5.0.7 on 2024-08-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0010_contracts_projects_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.contracts', verbose_name='договор'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='выполнено'),
        ),
        migrations.CreateModel(
            name='Adjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000, verbose_name='Объект согласования')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='дата отправки')),
                ('recieve_date', models.DateTimeField(blank=True, null=True, verbose_name='дата получениия')),
                ('is_agreed', models.BooleanField(blank=True, default=False, verbose_name='Согласовано')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.contracts', verbose_name='договор')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
