# Generated by Django 5.0.7 on 2024-09-03 20:16

import projectsapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0014_documents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(max_length=1000, upload_to='projects/contracts/docs/', validators=[projectsapp.validators.validate_docs_extension], verbose_name='Документ'),
        ),
    ]
