# Generated by Django 5.0.7 on 2024-09-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0015_alter_documents_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
    ]
