# Generated by Django 5.0.7 on 2025-01-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0016_alter_documents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата начала'),
        ),
    ]
