# Generated by Django 5.0.7 on 2025-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0019_alter_projects_actual_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjust',
            name='subject',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Объект согласования'),
        ),
    ]
