# Generated by Django 5.0.7 on 2026-08-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0020_alter_adjust_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjust',
            options={'verbose_name': 'согласований', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name': 'договоров', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'документов', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'проектов', 'verbose_name_plural': 'Проекты'},
        ),
    ]
