from decouple import Csv, config

DJANGO_SECRET_KEY = config("DJANGO_SECRET_KEY")
DJANGO_DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)
DJANGO_ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", cast=Csv(str))

DB_NAME = config("DB_NAME")
DB_USERNAME = config("DB_USERNAME")
DB_PASSWORD = config("DB_PASSWORD")
DB_HOST = config("DB_HOST")
DB_PORT = config("DB_PORT")

DJANGO_CORS_ALLOW_ALL_ORIGINS = config("DJANGO_CORS_ALLOW_ALL_ORIGINS", default=True, cast=bool)
DJANGO_CSRF_ALLOWED_ORIGINS = config("DJANGO_CSRF_ALLOWED_ORIGINS", cast=Csv(str))
DJANGO_CSRF_TRUSTED_ORIGINS = config("DJANGO_CSRF_TRUSTED_ORIGINS", cast=Csv(str))
DJANGO_CORS_ORIGINS_WHITELIST = config("DJANGO_CORS_ORIGINS_WHITELIST", cast=Csv(str))
CORS_ALLOWED_ORIGINS = ['http://*', 'https://*']

EMAIL_HOST = config("EMAIL_HOST")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_PORT = config("EMAIL_PORT")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")