services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - /home/indsol/app_data/data/db/pgdata:/var/lib/postgresql/pgdata
    privileged: true
    restart: always
    ports:
      - '5432:5432'

    environment:
      POSGRES_DB: 'indsol'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '7DXCVAEWpxwWsUsBMPmc'
      PGDATA: '/var/lib/postgresql/pgdata'

  backend:
    build: ./backend
    command: bash -c "
        python manage.py migrate &&
        gunicorn indsol_web.wsgi -b 0.0.0.0:8080"
    environment:
      DJANGO_SETTINGS_MODULE: indsol_web.settings.pre_production
    volumes:
      - /home/indsol/app_data/data/media:/app/media
      - /home/indsol/app_data/logs/:/app/logs
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db
  
  nginx:
    build: ./nginx
    privileged: true
    restart: always
    volumes:
     #  Данные ключи используются только при работе с certbot
     # - /home/indsol/Ind-strsolution_projects/nginx/cert.pem:/etc/cert.pem
     # - /home/indsol/Ind-strsolution_projects/nginx/key.pem:/etc/key.pem
      - /home/indsol/app_data/data/media:/var/www/media
      - /home/indsol/Ind-strsolution_projects/backend/static:/var/www/static
    ports:
      - 8000:80
      - 433:433
    depends_on:
      - backend

# Используется только при получении домена
#  certbot:
#    build: ./certbot
#    ports:
#      - '6000:80'
#    env_file:
#      - .env
#    # и снова мониторуем директорию nginx
#    volumes:
#      - /home/indsol/Ind-strsolution_projects/nginx/:/etc/nginx/

