services:
  # База данных PostgreSQL
  db:
    image: postgres:14.5-alpine
    volumes:
      - /home/indsol/app_data/data/db/pgdata:/var/lib/postgresql/pgdata
    privileged: true
    restart: always
    ports:
      - '5432:5432'


    environment:
      POSGRES_DB: 'indsol'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '7DXCVAEWpxwWsUsBMPmc'
      PGDATA: '/var/lib/postgresql/pgdata'

  # Бэкенд Django Rest Framework
  backend:
    build: ./backend
    command: bash -c "
        python manage.py migrate &&
        gunicorn indsol_web.wsgi -b 0.0.0.0:8080"
    environment:
      DJANGO_SETTINGS_MODULE: indsol_web.settings.pre_production
    volumes:
      - /home/indsol/Ind-strsolution_projects/backend/indsol_web/projectsapp/fixtures:/app/backend/projectsapp/fixtures
      - /home/indsol/app_data/data/media:/app/media
      - /home/indsol/app_data/logs/:/app/logs
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - redis
  
  # Веб-сервер nginx
  nginx:
    build: ./nginx
    privileged: true
    restart: always
    volumes:
        - /home/indsol/app_data/logs/nginx:/var/log/nginx
        - /home/indsol/Ind-strsolution_projects/frontend/build/static:/var/www/static
        #- /home/indsol/Ind-strsolution_projects/backend/indsol_web/static:/var/www/static
        - /home/indsol/app_data/data/media:/var/www/media
        - /etc/ssl/certs/ipm-portal/:/var/certs/
    ports:
      - 8000:80
      - 443:443
    depends_on:
      - backend

  # Фроненд React
  frontend:
    build: ./frontend
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on: 
      - nginx

  # NoSQL база данных
  redis:
    image: redis:alpine

  # Обработчик задач  
  celery:
    build: ./backend
    command: celery -A indsol_web worker -l info
    restart: always
    volumes:
      - /home/indsol/Ind-strsolution_projects/backend/indsol_web/projectsapp/fixtures:/app/backend/projectsapp/fixtures
      - /home/indsol/app_data/data/media:/app/media
      - ./project/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  # Планировщик периодических задач    
  celery-beat:
    build: ./backend
    command: celery -A indsol_web beat -l info
    restart: always
    volumes:
      - /home/indsol/Ind-strsolution_projects/backend/indsol_web/projectsapp/fixtures:/app/backend/projectsapp/fixtures
      - /home/indsol/app_data/data/media:/app/media
      - ./project/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  # Мониторинг периодических задач
  flower:
    build: ./backend
    command: celery -A indsol_web flower -l info
    restart: always
    volumes:
      - /home/indsol/app_data/data/media:/app/media
      - ./project:/usr/src/app/
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - celery
      - redis

