# Generated by Django 4.2.1 on 2024-04-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Звголовок')),
                ('text', models.TextField(max_length=40000, verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='MediaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='', verbose_name=models.FileField(upload_to='news/media', verbose_name='файлы'))),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='newsapp.news')),
            ],
        ),
    ]
