# Generated by Django 4.2.1 on 2024-04-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaNews',
            new_name='Media',
        ),
    ]
