# Generated by Django 4.2.1 on 2024-04-23 11:34

from django.db import migrations, models
import newsapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to='news/media/', validators=[newsapp.validators.validate_media_extension], verbose_name='файлы'),
        ),
    ]
