# Generated by Django 4.2.1 on 2024-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_media_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsline',
            field=models.BooleanField(default=False, verbose_name='Добавить в лениу'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
