# Generated by Django 4.2.1 on 2024-07-10 14:22

from django.db import migrations, models
import newsapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_news_newsline_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(default=1, upload_to='news/covers/', validators=[newsapp.validators.validate_media_extension], verbose_name='обложка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='to_slider',
            field=models.BooleanField(default=False, verbose_name='Добавить в миниленту'),
        ),
    ]
