# Generated by Django 4.2.1 on 2024-07-12 19:53

from django.db import migrations, models
import newsapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_remove_news_newsline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/', validators=[newsapp.validators.validate_media_extension], verbose_name='обложка'),
        ),
    ]
