# Generated by Django 4.2.1 on 2024-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_news_publicated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publicated_at',
            field=models.DateTimeField(verbose_name='дата публикации'),
        ),
    ]
