# Generated by Django 4.2.1 on 2024-04-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0003_menu_wiki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='wiki',
            new_name='wiki_id',
        ),
    ]
