# Generated by Django 4.2.1 on 2024-04-08 14:49

from django.db import migrations, models
import django.db.models.deletion
import wikiapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование статьи')),
                ('text', models.TextField(max_length=100000, verbose_name='текст статьи')),
                ('is_article', models.BooleanField(default=False, verbose_name='видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='files/img/', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('img', models.FileField(blank=True, null=True, upload_to='icons/menu/', validators=[wikiapp.validators.validate_svg_extension], verbose_name='иконка')),
                ('is_article', models.BooleanField(default=False, verbose_name='видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='files/video/', validators=[wikiapp.validators.validate_video_extension], verbose_name='видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='раздел')),
                ('img', models.FileField(blank=True, null=True, upload_to='icons/sections/', validators=[wikiapp.validators.validate_svg_extension], verbose_name='иконка')),
                ('is_article', models.BooleanField(default=False, verbose_name='видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.menu', verbose_name='id меню')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Разделы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название файла')),
                ('file', models.FileField(upload_to='files/', verbose_name='файлы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wikiapp.articles', verbose_name='id статья')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wikiapp.menu', verbose_name='id меню'),
        ),
        migrations.AddField(
            model_name='articles',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wikiapp.sections', verbose_name='id раздел'),
        ),
    ]
