# Generated by Django 4.2.1 on 2024-06-10 20:31

from django.db import migrations, models
import wikiapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0004_rename_wiki_menu_wiki_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='wiki/files/', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='wiki/articles/img/', verbose_name='изображения'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='wiki/icons/sections/', validators=[wikiapp.validators.validate_svg_extension], verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='wiki/articles/video/', validators=[wikiapp.validators.validate_video_extension], verbose_name='видео'),
        ),
    ]
