# Generated by Django 4.2.1 on 2024-07-13 15:07

from django.db import migrations, models
import wikiapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0006_alter_menu_wiki_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='icons/logo/', validators=[wikiapp.validators.validate_svg_extension], verbose_name='иконка'),
        ),
    ]
