# Generated by Django 4.2.1 on 2024-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0008_alter_menu_img_alter_wiki_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='wiki/articles/files/', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(max_length=1000, upload_to='wiki/articles/img/', verbose_name='изображения'),
        ),
    ]
