# Generated by Django 5.0.7 on 2024-10-30 20:24

import wikiapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0009_alter_files_file_alter_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(max_length=1000, upload_to='wiki/articles/files/', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(max_length=1000, upload_to='wiki/articles/video/', validators=[wikiapp.validators.validate_video_extension], verbose_name='видео'),
        ),
    ]
