# Generated by Django 5.0.7 on 2025-08-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0012_wiki_owner_wiki_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='owner',
        ),
    ]
