# Generated by Django 5.0.7 on 2025-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0013_remove_wiki_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
            ],
        ),
    ]
