# Generated by Django 5.0.7 on 2025-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0014_menu_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='sections',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
