# Generated by Django 5.0.7 on 2026-08-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0015_articles_order_menu_order_sections_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['created_at'], 'verbose_name': 'статей', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['created_at'], 'verbose_name': 'файлов', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'изображений', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['created_at'], 'verbose_name': 'разделов', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['created_at'], 'verbose_name': 'подразделов', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['created_at'], 'verbose_name': 'списка вики', 'verbose_name_plural': 'Wiki'},
        ),
    ]
