# Generated by Django 5.0.7 on 2026-10-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0016_alter_articles_options_alter_files_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiapp.articles', verbose_name='id статьи'),
        ),
        migrations.AddField(
            model_name='videos',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiapp.articles', verbose_name='id статьи'),
        ),
    ]
