# Generated by Django 4.2.1 on 2024-07-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_user_clients_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='agreement',
        ),
        migrations.CreateModel(
            name='Сontracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, verbose_name='номер договора')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.clients', verbose_name='клиент')),
            ],
        ),
    ]
