# Generated by Django 4.2.1 on 2024-07-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_clients_agreement_сontracts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сontracts',
            new_name='Contracts',
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name': 'Договоры', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Менеджеры', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_id', to='authapp.branches', verbose_name='отрасль'),
        ),
    ]
