# Generated by Django 5.0.7 on 2024-08-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_contracts_id_alter_contracts_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='client_id',
        ),
    ]
