# Generated by Django 5.0.7 on 2024-08-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_contracts_client_id'),
        ('projectsapp', '0007_contracts_alter_projects_contract_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contracts',
        ),
    ]
