# Generated by Django 5.2.9 on 2025-12-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_groups_users_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='ru_name',
            field=models.CharField(default='dd', max_length=200, verbose_name='наименование роли(ru)'),
            preserve_default=False,
        ),
    ]
