# Generated by Django 5.0.7 on 2026-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_groups_ru_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='group',
        ),
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='authapp.groups', verbose_name='группы'),
        ),
    ]
