# Generated by Django 5.0.7 on 2026-07-14 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_alter_users_groups'),
        ('wikiapp', '0015_articles_order_menu_order_sections_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=False, verbose_name='Создание')),
                ('read', models.BooleanField(default=False, verbose_name='Чтение')),
                ('update', models.BooleanField(default=False, verbose_name='Обновление')),
                ('delete', models.BooleanField(default=False, verbose_name='Удаление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.wiki', verbose_name='wiki_id')),
            ],
        ),
    ]
