# Generated by Django 5.0.7 on 2026-07-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_wikipermissions'),
        ('wikiapp', '0015_articles_order_menu_order_sections_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikiPermissions',
            new_name='Wiki_Permissions',
        ),
        migrations.AlterModelOptions(
            name='wiki_permissions',
            options={'verbose_name': 'Разрешения вики', 'verbose_name_plural': 'Разрешения вики'},
        ),
    ]
