# Generated by Django 5.0.7 on 2026-07-15 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_rename_wikipermissions_wiki_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_Group_Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование групп разрешений Wiki')),
            ],
        ),
        migrations.RemoveField(
            model_name='wiki_permissions',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='wiki_groups',
            field=models.ManyToManyField(blank=True, to='authapp.wiki_group_permissions', verbose_name='Группы Вики'),
        ),
        migrations.AddField(
            model_name='wiki_permissions',
            name='wiki_group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='authapp.wiki_group_permissions', verbose_name='wiki_group_id'),
        ),
    ]
