# Generated by Django 5.0.7 on 2026-07-15 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_wiki_group_permissions_remove_wiki_permissions_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='wiki_groups',
        ),
        migrations.AddField(
            model_name='users',
            name='wiki_group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='authapp.wiki_group_permissions', verbose_name='Группы Вики'),
        ),
        migrations.AlterField(
            model_name='wiki_permissions',
            name='wiki_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.wiki_group_permissions', verbose_name='wiki_group_id'),
        ),
    ]
