# Generated by Django 5.0.7 on 2026-08-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_remove_users_wiki_groups_users_wiki_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wiki_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authapp.wiki_group_permissions', verbose_name='Группы Вики'),
        ),
    ]
