# Generated by Django 5.0.7 on 2026-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_alter_users_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, to='authapp.groups', verbose_name='группы'),
        ),
    ]
