# Generated by Django 5.0.7 on 2026-08-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_alter_users_wiki_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'ordering': ['name'], 'verbose_name': 'отраслей', 'verbose_name_plural': 'Отрасли'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'профилей клиентов', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='districts',
            options={'ordering': ['name'], 'verbose_name': 'федеральнго округа', 'verbose_name_plural': 'Федеральный округ'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'групп прав', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'профилей менеджеров', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['created_at'], 'verbose_name': 'пользователей', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='wiki_group_permissions',
            options={'verbose_name': 'групп прав вики', 'verbose_name_plural': 'Группы прав вики'},
        ),
        migrations.AlterModelOptions(
            name='wiki_permissions',
            options={'verbose_name': 'прав вики', 'verbose_name_plural': 'прав вики'},
        ),
    ]
