# Generated by Django 4.2.1 on 2024-07-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_news_cover_news_to_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newsline',
        ),
    ]
