# Generated by Django 4.2.1 on 2024-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_news_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publicated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата публикации'),
        ),
    ]
