# Generated by Django 5.0.7 on 2024-09-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_alter_news_publicated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Файлы новостей', 'verbose_name_plural': 'Файлы новостей'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
