# Generated by Django 5.0.7 on 2024-09-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_media_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
