# Generated by Django 5.0.7 on 2024-10-30 20:24

import newsapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(max_length=1000, upload_to='news/media/', validators=[newsapp.validators.validate_media_extension], verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='news/covers/', validators=[newsapp.validators.validate_media_extension], verbose_name='обложка'),
        ),
    ]
