# Generated by Django 5.0.7 on 2026-08-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_alter_media_media_alter_news_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'медиа файлов новостей', 'verbose_name_plural': 'Файлы новостей'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'verbose_name': 'новостей', 'verbose_name_plural': 'Новости'},
        ),
    ]
