# Generated by Django 5.0.7 on 2026-08-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_alter_media_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'медиа файлов', 'verbose_name_plural': 'Файлы новостей'},
        ),
    ]
