# Generated by Django 5.0.7 on 2024-08-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_alter_projects_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок выполнения'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_completed',
            field=models.BooleanField(default=False, null=True, verbose_name='выполнено'),
        ),
    ]
