# Generated by Django 5.0.7 on 2024-08-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_alter_projects_deadline_alter_projects_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='responsible',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ответственный'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='responsible_rp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ответственный рп'),
        ),
    ]
