# Generated by Django 5.0.7 on 2024-08-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_alter_projects_responsible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='updated_at',
        ),
    ]
