# Generated by Django 5.0.7 on 2024-08-05 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_contracts_client_id'),
        ('projectsapp', '0006_alter_projects_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='номер договора')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.clients', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Договоры',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projectsapp.contracts', verbose_name='договор'),
        ),
    ]
