# Generated by Django 5.0.7 on 2024-08-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0011_alter_projects_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='номер договора'),
        ),
    ]
