# Generated by Django 5.0.7 on 2024-09-02 19:00

import django.db.models.deletion
import projectsapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0012_alter_contracts_contract_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='projects/contracts/docs/', validators=[projectsapp.validators.validate_docs_extension], verbose_name='видео')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.contracts', verbose_name='договор')),
            ],
        ),
    ]
