# Generated by Django 5.0.7 on 2025-01-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0017_alter_projects_name_alter_projects_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок выполнения'),
        ),
    ]
