# Generated by Django 5.0.7 on 2025-01-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0018_alter_projects_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='actual_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата фактического выполнения'),
        ),
    ]
